# -*- coding: utf-8 -*-
"""Student performance analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Y3BMpAIrswg4-Rt7fhVkMXSaBeeIUGg
"""

ls /content/drive/MyDrive/

CSV_PATH = "/content/drive/MyDrive/student-scores.csv"

df.head()

df.info()

df.columns

df

df.describe()

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

df = pd.read_csv(CSV_PATH)

plt.figure(figsize=(10,6))
sns.histplot(
    df["weekly_self_study_hours"],
    bins=30,
    kde=True,
    color="lightblue",
    edgecolor="black"
)
plt.title("Distribution of Weekly Self-Study Hours", fontsize=14, weight="bold")
plt.xlabel("Weekly Self-Study Hours", fontsize=12)
plt.ylabel("Number of Students", fontsize=12)
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

gender_counts = df['gender'].value_counts()
ax = gender_counts.plot(kind='barh', title='Students Gender', color=['lightpink', 'lightblue']) # Assuming 'female' is the first count and 'male' is the second based on previous output
ax.set_ylabel('Gender')
ax.set_xlabel('Count')
print(gender_counts)

plt.figure(figsize=(8, 6))
sns.barplot(x='part_time_job', y='cum_score', data=df, palette='viridis', errorbar='sd') # Use barplot with standard deviation error bars
plt.title('Average Cumulative Score by Part-Time Job Status', fontsize=16, weight='bold')
plt.xlabel('Has Part-Time Job', fontsize=14)
plt.ylabel('Average Cumulative Score', fontsize=14)
plt.xticks([0, 1], ['No Part-Time Job', 'Has Part-Time Job'])
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,6))
df["extracurricular_activities"].value_counts().plot(
    kind="pie",
    autopct="%1.0f%%",
    startangle=90,
    colors=["lightblue","lightgreen"]
)
plt.title("Extracurricular Activities Participation", fontsize=14, weight="bold")
plt.ylabel("")
plt.axis("equal")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,10)) # Increased figure size
df["career_aspiration"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%", # Changed to one decimal place for percentage
    startangle=90,
    cmap="tab20",
    pctdistance=0.85, # Adjust distance of percentage labels
    labeldistance=1.02 # Adjust distance of category labels
)
plt.title("Career Aspirations", fontsize=16, weight="bold") # Increased title font size
plt.ylabel("")
plt.axis("equal")
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,7))
sns.boxplot(
    x="career_aspiration",
    y="weekly_self_study_hours",
    data=df,
    palette="pastel"
)
plt.title("Weekly Self-Study Hours by Career Aspiration", fontsize=14, weight="bold")
plt.xlabel("Career Aspiration", fontsize=12)
plt.ylabel("Weekly Self-Study Hours", fontsize=12)
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.show()

subjects = [
    "math_score","history_score","physics_score",
    "chemistry_score","biology_score","english_score","geography_score"
]

stats_df = pd.DataFrame({
    "Min": df[subjects].min(),
    "Average": df[subjects].mean(),
    "Max": df[subjects].max()
})

print("\n=== Subject Stats (Min / Average / Max) ===")
print(stats_df.round(2))

x = np.arange(len(subjects))
width = 0.28
fig, ax = plt.subplots(figsize=(12,6))
ax.bar(x - width, stats_df["Min"], width, label="Min", color="lightcoral")
ax.bar(x,         stats_df["Average"], width, label="Average", color="skyblue")
ax.bar(x + width, stats_df["Max"], width, label="Max", color="lightgreen")

ax.set_title("Min / Average / Max by Subject", fontsize=14, weight="bold")
ax.set_xticks(x)
ax.set_xticklabels(subjects, rotation=30, ha="right", fontsize=11)
ax.set_ylabel("Score", fontsize=12)
ax.legend()
plt.grid(axis="y", linestyle="--", alpha=0.5)
plt.tight_layout()
plt.show()